// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8_Bg5_Ryfoo23bwEzZzrh4nICygcFrjo',
    appId: '1:439877939242:web:93f0b68194243bc9e55353',
    messagingSenderId: '439877939242',
    projectId: 'specltd-eef09',
    authDomain: 'specltd-eef09.firebaseapp.com',
    storageBucket: 'specltd-eef09.appspot.com',
    measurementId: 'G-S6K89TPDF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt9_PhAg4THABDu0M1sXvQQTeBqDg8kp0',
    appId: '1:439877939242:android:e20d0b04a7a2b075e55353',
    messagingSenderId: '439877939242',
    projectId: 'specltd-eef09',
    storageBucket: 'specltd-eef09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbjzlX3HIhJtQcszUE1sA6SWIA02EqxlY',
    appId: '1:439877939242:ios:a533e7577c84e153e55353',
    messagingSenderId: '439877939242',
    projectId: 'specltd-eef09',
    storageBucket: 'specltd-eef09.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbjzlX3HIhJtQcszUE1sA6SWIA02EqxlY',
    appId: '1:439877939242:ios:a533e7577c84e153e55353',
    messagingSenderId: '439877939242',
    projectId: 'specltd-eef09',
    storageBucket: 'specltd-eef09.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8_Bg5_Ryfoo23bwEzZzrh4nICygcFrjo',
    appId: '1:439877939242:web:f3192f0a0e0c14c8e55353',
    messagingSenderId: '439877939242',
    projectId: 'specltd-eef09',
    authDomain: 'specltd-eef09.firebaseapp.com',
    storageBucket: 'specltd-eef09.appspot.com',
    measurementId: 'G-YVCTQ57Y26',
  );

}